### PR TITLE
15446 add metrics

### LINKED ISSUE #15446: Implement placeholder opt-in metrics checkbox at the start of onboarding for new users and backend
### Description

status-go PR: https://github.com/status-im/status-go/pull/5477
(mostly ready now)

Once the status-go PR above is ready, we can start working on adding a placeholder checkbox on the onboarding for new users to opt in sending metrics.

This setting will be global for the installation/device. It needs to be before the sign in and login, because we want to track the onboarding metrics too.

Make it placeholder as we'll get the designs later.

### Acceptance Criteria

- There is a switch or button on the first screen of onboarding that let's users opt-in to sending metrics
- If it is activated, the API on status-go is activated
- No need to have the deactivation for now until we have the designs
- No need to think about old users upgrading for now. Make it for new users only for now

### PR DESCRIPTION
**Pull request by endulab**
Replace openAccounts with InitializeAppliaction.
Add centralized metrics functions.

Issue https://github.com/status-im/status-desktop/issues/15446

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Why was @igor-sirotin 's PR not merged?

**Comment by endulab** [comment]
> Why was @igor-sirotin 's PR not merged?

What pr? In nim-status-go lib?

**Comment by jrainville** [comment]
> > Why was @igor-sirotin 's PR not merged?
> 
> What pr? In nim-status-go lib?

This one : https://github.com/status-im/nim-status-go/pull/30

You have a commit from it in your PR

**Comment by endulab** [comment]
> > > Why was @igor-sirotin 's PR not merged?
> > 
> > 
> > What pr? In nim-status-go lib?
> 
> This one : #30
> 
> You have a commit from it in your PR

Wow, ok, some rebase issue. Now it is ok.

**Comment by igor-sirotin** [comment]
oops, just forgot to merge https://github.com/status-im/nim-status-go/pull/30

**Pull request merged**
